---
- name: Set app variables
  set_fact:
    app_name: "magicmirror"
    port: "40245"

- name: Configure {{ app_name }}
  block:
    - name: Create app folders
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
      - /src/{{ app_name }}
      - /mnt/root/config/{{ app_name }}/config
      - /mnt/root/config/{{ app_name }}/modules
      - /mnt/root/config/{{ app_name }}/css

    - name: Copy docker files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - src: "{{ app_name }}_docker-compose.yml.j2"
          dest: "/src/{{ app_name }}/docker-compose.yml"

    - name: Create and start {{ app_name }}
      community.docker.docker_compose_v2:
        project_src: /src/{{ app_name }}

    - name: Check if the {{ app_name }}.home resolves
      getent:
        database: hosts
        key: "{{ app_name }}.home"
      register: hostname_check
      ignore_errors: yes

    - name: Run script to add {{ app_name }}.home to technitium
      script: technitium_script.sh -h {{ app_name }} -i {{ ansible_ens18.ipv4.address }}
      when: hostname_check.failed
      environment:
        TECHNITIUM_API_TOKEN: "{{ TECHNITIUM_API_TOKEN }}"