---
- name: Install apt dependences
  ansible.builtin.apt:
    pkg:
      - openvpn
      - unzip
    cache_valid_time: 86400 # One day

- name: Download PIA OpenVPN configuration files
  ansible.builtin.get_url:
    url: https://www.privateinternetaccess.com/openvpn/openvpn.zip
    dest: ~/openvpn.zip
    validate_certs: false

- name: Create folder to extract to
  ansible.builtin.file:
    path: ~/pia_openvpn_profiles
    state: directory

- name: Extract .zip file
  ansible.builtin.unarchive:
    src: ~/openvpn.zip
    dest: ~/pia_openvpn_profiles
    remote_src: true

- name: Create login.txt
  ansible.builtin.template:
    src: login.txt.j2
    dest: /etc/openvpn/login.txt
    mode: '700'
  no_log: true

- name: Create init.d startup script file
  ansible.builtin.copy:
    src: openvpnauto
    dest: /etc/init.d/openvpnauto
    mode: +x
  notify: Restart openvpnauto

- name: Add route for 10.0.0.0/24
  ansible.builtin.file:
    src: local_route
    dest: /etc/network/if-up.d/local_route
    mode: "751"

- name: Make sure openvpnauto is started
  ansible.builtin.systemd_service:
    name: openvpnauto
    state: started
    enabled: yes
    daemon_reload: true
