version: "3.2"
services:
  radarr:
    container_name: radarr
    user: root:root
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/root/config/radarr:/config
      - /mnt/root/Transmission:/data/torrents
      - /mnt/root/Plex:/data/media
  sonarr:
    container_name: sonarr
    user: root:root
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/root/config/sonarr:/config
      - /mnt/root/Transmission:/data/torrents
      - /mnt/root/Plex:/data/media