---
shares:
    - name: pve-share
      mount: /mnt/pve-share

    - name: plex
      mount: /mnt/pve-share/Plex

    - name: librarian
      mount: /mnt/pve-share/Media/Books

    - name: vscode-server
      mount: /mnt/pve-share/Git