---
- name: Install wireguard
  ansible.builtin.apt:
    pkg:
      - resolvconf
      - iptables
      - wireguard

- name: Create symbolic link for resolv.conf
  file:
    src: /run/resolvconf/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true

- name: Copy wireguard config
  ansible.builtin.template:
    src: us-atl-wg-002.conf.j2
    dest: /etc/wireguard/us-atl-wg-002.conf
  notify: Restart wireguard

- name: Ensure network scripts directory exists
  file:
    path: /etc/network/if-up.d
    state: directory
    mode: '0755'

- name: Create permanent route script
  copy:
    dest: /etc/network/if-up.d/custom-routes
    mode: '0751'
    content: |
      #!/bin/sh
      ip route add 10.0.0.0/16 via 10.0.11.1 || true
  notify: Restart networking

- name: Ensure wireguard is started
  ansible.builtin.systemd:
    name: wg-quick@us-atl-wg-002
    state: started
    enabled: true