- name: Set up Caddy
  hosts: firewall
  tasks:
    - name: Add apps to technitium
      ansible.builtin.script: technitium_script.sh -h {{ hostvars.vars.app }} -d firewall.home
      loop: "{{ apps }}"
      environment:
        TECHNITIUM_API_TOKEN: "{{ TECHNITIUM_API_TOKEN }}"
      delegate_to: localhost

    - name: Create Caddy configs for services
      ansible.builtin.copy:
        dest: "/usr/local/etc/caddy/caddy.d/{{ item.hostname.split('.')[0] }}.conf"
        mode: '0644'
        content: |
          {{ item.hostname }}:80 {
              reverse_proxy {{ item.upstream_host }}:{{ item.port }}
          }
      notify: Restart caddy
      loop: "{{ apps }}"
  
  handlers:
    - name: Restart caddy
      ansible.builtin.service:
        name: caddy
        state: restarted