---
- name: Setup VS Code Server
  hosts: code.home
  vars:
    user: code
  roles:
    - update
    - dotnet

  tasks:
    - name: Install apt dependencies
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400 # One day
        pkg:
          - python3-pip
          - python3-venv
          - gpg

    - name: Create group - {{ user }}
      ansible.builtin.group:
        name: "{{ user }}"
        gid: 101111
        state: present

    - name: Create user - {{ user }}
      ansible.builtin.user:
        name: "{{ user }}"
        uid: 101111
        groups: "{{ user }}"
        append: true

    - name: Download HashiCorp GPG key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
        mode: '0644'

    - name: Add HashiCorp repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present

    # - name: Download Nodesource GPG key
    #   ansible.builtin.get_url:
    #     url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    #     dest: /usr/share/keyrings/nodesource.gpg
    #     mode: '0644'

    # - name: Add Nodesource repository
    #   ansible.builtin.apt_repository:
    #     repo: "deb [signed-by=/usr/share/keyrings/nodesource.asc] https://deb.nodesource.com/node_22.x nodistro main"
    #     state: present

    - name: Install tools
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400 # One day
        pkg:
          - ansible
          - terraform
          - azure-cli
          - nodejs

    - name: Copy SSH keys
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ item }}"
        mode: '0400'
      loop:
        - ~/.ssh/pve-server
        - ~/.ssh/pve-server.pub

- name: Update LXC .conf
  ansible.builtin.import_playbook: lxc_conf.yml
  vars:
    id: "{{ hostvars['code.home']['container_id_fact'] }}"
    lxc_config_block: |
      mp0: /storage/git:/mnt/git
