---
- name: Setup Postgres instance
  hosts: db.home
  gather_facts: false
  roles:
    - update

  tasks:
    - name: Install apt dependencies
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - postgresql
          - python3-pip
          - sudo
          - rsync

    - name: Install pip dependencies
      ansible.builtin.pip:
        name: psycopg2-binary
        extra_args: --break-system-packages

    - name: Configure Postgresql
      become: true
      become_user: postgres
      block:
        - name: Set listen_addresses
          community.postgresql.postgresql_set:
            name: listen_addresses
            value: "*"
          notify: Restart postgresql

        - name: Grant access from network
          community.postgresql.postgresql_pg_hba:
            dest: /etc/postgresql/15/main/pg_hba.conf
            contype: host
            users: all
            source: 10.0.0.0/16
            databases: all
            method: md5
          notify: Restart postgresql

  handlers:
    - name: Restart postgresql
      ansible.builtin.service:
        name: postgresql
        state: restarted
