---
- name: Preconfigure download
  hosts: download.home
  vars:
    - user: downloader
  roles:
    - update

- name: Update LXC .conf
  ansible.builtin.import_playbook: lxc_conf.yml
  vars:
    id: "{{ hostvars['download.home']['container_id_fact'] }}"
    lxc_config_block: |
      mp0: /storage/Downloads,mp=/mnt/downloads

- name: Setup downloaders
  hosts: download.home
  vars:
    - user: downloader
  tasks:
    - name: Create group - {{ user }}
      ansible.builtin.group:
        name: "{{ user }}"
        gid: 1111
        state: present

    - name: Create user - {{ user }}
      ansible.builtin.user:
        name: "{{ user }}"
        uid: 1111
        group: "{{ user }}"

    - name: Install software-properties-common
      ansible.builtin.apt:
        pkg:
          - software-properties-common
        update_cache: true

    - name: Add contrib non-free repository
      ansible.builtin.apt_repository:
        repo: "deb http://deb.debian.org/debian/ {{ ansible_distribution_release }} main contrib non-free"
        state: present

    - name: Install dependencies
      ansible.builtin.apt:
        pkg:
          - unrar
          - libavahi-compat-libdnssd1
          - p7zip-full
          - python3-notify2

    - name: Install sabnzbdplus
      ansible.builtin.apt:
        pkg:
          - sabnzbdplus

    - name: Set sabnzbdplus systemd
      ansible.builtin.lineinfile:
        path: /etc/default/sabnzbdplus
        regexp: "{{ item.reg }}"
        line: "{{ item.line }}"
      with_items:
        - reg: '^USER'
          line: "USER={{ user }}"
        - reg: '^HOST'
          line: "HOST={{ inventory_hostname }}"
      notify: Restart sabnzbdplus

    - name: Configure sabnzbdplus settings
      ansible.builtin.replace:
        path: "/home/{{ user }}/.sabnzbd/sabnzbd.ini"
        regexp: "{{ item.reg }}"
        replace: "{{ item.replace }}"
      loop:
        - reg: '^host = .*$'
          replace: "host = {{ inventory_hostname }}"
        - reg: '^host_whitelist = .*$'
          replace: "host_whitelist = {{ inventory_hostname }}"
        - reg: '^username = .*$'
          replace: 'username = "cmeadows"'
        - reg: '^password = .*$'
          replace: 'password = "{{ password }}"'
      notify: Restart sabnzbdplus

    - name: Ensure sabnzbdplus is started
      ansible.builtin.service:
        name: sabnzbdplus
        state: started
        enabled: true

    - name: Transmission
      block:
        - name: Install dependencies
          ansible.builtin.apt:
            pkg:
              - transmission-cli
              - transmission-common
              - transmission-daemon

        - name: Ensure sabnzbdplus is started
          ansible.builtin.service:
            name: transmission-daemon
            state: started
            enabled: true

  handlers:
    - name: Restart sabnzbdplus
      ansible.builtin.service:
        name: sabnzbdplus
        state: restarted
    
    - name: Restart transmission
      ansible.builtin.service:
        name: transmission-daemon
        state: transmission-daemon
