---
- name: Setup Flame dashboard
  hosts: flame
  gather_facts: false
  roles:
    - update

  tasks:
    - name: Install apt dependencies
      ansible.builtin.apt:
        pkg:
          - git
    
    - name: Download Nodesource GPG key
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        dest: /usr/share/keyrings/nodesource.asc
        mode: '0644'

    - name: Add Nodesource repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/nodesource.asc] https://deb.nodesource.com/node_20.x nodistro main"
        state: present

    - name: Install tools
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400 # One day
        pkg:
          - nodejs
    
    - name: Make /src/flame folder
      ansible.builtin.file:
        path: /src/flame
        state: directory

    - name: Mark directory as safe
      ansible.builtin.command: git config --global --add safe.directory /src/flame

    - name: Clone flame repro
      ansible.builtin.git:
        repo: https://github.com/fdarveau/flame.git
        dest: /src/flame
        clone: true
        force: true
    
    - name: Install flame dependencies
      community.general.npm:
        name: "{{ item.name }}"
        path: "{{ item.path }}"
      with_items:
        - name: dev-init
          path: /src/flame
        - name: build
          path: /src/flame/client

    - name: Build flame
      ansible.builtin.shell: npm run build
      args:
        chdir: /src/flame/client
    
    - name: Make data and public directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - /src/flame/data
        - /src/flame/public

    - name: Copy files from client/build to public
      ansible.builtin.copy:
        remote_src: true
        src: /src/flame/client/build/
        dest: /src/flame/public/
    
    - name: Set flame .env variables
      ansible.builtin.lineinfile:
        path: /src/flame/.env
        regexp: "{{ item.reg }}"
        line: "{{ item.line }}"
      with_items:
        - reg: '^NODE_ENV'
          line: NODE_ENV=production
        - reg: '^PASSWORD'
          line: PASSWORD={{ password }}

    - name: Copy flame.service file
      ansible.builtin.copy:
        src: ./files/flame.service
        dest: /etc/systemd/system/flame.service

    - name: Make sure flame is running
      ansible.builtin.systemd:
        state: started
        enabled: true
        name: flame
        daemon_reload: true

    