---
- name: Setup Jellyfin server
  hosts: jellyfin
  vars:
    user: jellyfin
  roles:
    - update
    - fstab

  tasks:
    - name: Download Jellyfin GPG key
      ansible.builtin.get_url:
        url: https://repo.jellyfin.org/jellyfin_team.gpg.key
        dest: /usr/share/keyrings/jellyfin_team.asc
        mode: '0644'

    - name: Add Jellyfin repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jellyfin_team.asc] https://repo.jellyfin.org/debian {{ ansible_distribution_release }} main"
        state: present

    - name: Install jellyfin
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400 # One day
        pkg:
          - jellyfin

    - name: Ensure Jellyfin uses the jellyfin user
      ansible.builtin.lineinfile:
        path: /etc/systemd/system/jellyfin.service.d/jellyfin.service.conf
        regexp: '^#User'
        line: User = jellyfin
      notify: Restart Jellyfin

    - name: Make sure calibre-web is running
      ansible.builtin.systemd:
        name: jellyfin
        state: started
        enabled: true
        daemon_reload: true