---
- name: Setup Jellyfin server
  hosts: jellyfin
  vars:
    user: jellyfin
  roles:
    - update
    - fstab
    - tailscale

  tasks:
    - name: Download Jellyfin GPG key
      ansible.builtin.get_url:
        url: https://repo.jellyfin.org/jellyfin_team.gpg.key
        dest: /usr/share/keyrings/jellyfin_team.asc
        mode: '0644'

    - name: Add Jellyfin repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jellyfin_team.asc] https://repo.jellyfin.org/debian {{ ansible_distribution_release }} main"
        state: present
    
    # https://rocmdocs.amd.com/en/latest/deploy/linux/quick_start.html#ubuntu

    - name: Download Radeon GPG key
      ansible.builtin.get_url:
        url: https://repo.radeon.com/rocm/rocm.gpg.key
        dest: /usr/share/keyrings/rocm.asc
        mode: '0644'

    - name: Add Radeon repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/rocm.asc] https://repo.radeon.com/rocm/apt/debian jammy main"
        state: present

    - name: Install jellyfin
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400 # One day
        pkg:
          - jellyfin
          - jellyfin-ffmpeg5
          - vainfo
          - mesa-va-drivers
          - rocm-opencl-runtime
          - qemu-guest-agent
    
    - name: Add {{ user }} to groups
      ansible.builtin.user:
        name: jellyfin
        shell: /bin/bash
        groups: jellyfin,video,render
        append: yes
      notify: Restart Jellyfin

    - name: Ensure Jellyfin uses the jellyfin user
      ansible.builtin.lineinfile:
        path: /etc/systemd/system/jellyfin.service.d/jellyfin.service.conf
        regexp: '^#User'
        line: User = jellyfin
      notify: Restart Jellyfin

    - name: Make sure jellyfin is running
      ansible.builtin.systemd:
        name: jellyfin
        state: started
        enabled: true
        daemon_reload: true
  
  handlers:
    - name: Restart Jellyfin
      ansible.builtin.service:
        name: jellyfin
        state: restarted
