---
- name: Update .conf
  hosts: pve_server
  vars:
    conf_file: "/etc/pve/lxc/{{ id }}.conf"
    sandbox_dir: "~/config_sandbox"
    sandbox_file: "{{ sandbox_dir }}/{{ id }}.conf.meta"
  tasks:
    - name: Create directory
      ansible.builtin.file:
        path: "{{ sandbox_dir }}"
        state: directory
        mode: '0755'
        recurse: true
      register: sandbox_folder

    - name: Sandbox .conf.meta changes
      ansible.builtin.blockinfile:
        path: "{{ sandbox_file }}"
        block: "{{ lxc_config_block }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - LXC NVIDIA CONFIG"
        create: true
      register: sandbox_file

    - name: Combine files without duplicates
      # when: sandbox_file.changed
      block:
        - name: Read {{ conf_file }}
          ansible.builtin.slurp:
            src: "{{ conf_file }}"
          register: conf_file_content

        - name: Create lists
          ansible.builtin.set_fact:
            conf_content: "{{ (conf_file_content.content | b64decode | split('\n')) }}"
            sandbox_file: "{{ (lxc_config_block | split('\n')) }}"

        - name: Combine files and remove duplicates
          ansible.builtin.copy:
            content: "{{ ((conf_content + sandbox_file) | unique) | join('\n') }}"
            dest: "{{ conf_file }}"
          notify: Restart LXC

  handlers:
    - name: Restart LXC
      ansible.builtin.command: pct reboot {{ id }}
