---
- name: Modfy LXC .conf
  hosts: pve_server
  tasks:
    - name: Add LXC configuration entries
      ansible.builtin.blockinfile:
        path: "/etc/pve/lxc/{{ id }}.conf"
        block: "{{ lxc_config_block }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - LXC NVIDIA CONFIG"
        create: true
      register: config_check

  handlers:
    - name: Restart LXC
      ansible.builtin.command: pct reboot {{ id }}
      when: config_changes.changed
