---
- name: Preconfigure paperless
  hosts: paperless.home
  roles:
    - update
    - docker_compose

- name: Update LXC .conf
  ansible.builtin.import_playbook: lxc_conf.yml
  vars:
    id: "{{ hostvars.vars.container_id_fact }}"
    lxc_config_block: |
      mp0: /storage/Documents,mp=/mnt/documents

- name: Setup paperless
  hosts: paperless.home 
  vars:
    app: paperless
  tasks:
    - name: Create user
      ansible.builtin.group:
        name: "{{ app }}"
        gid: 1111
        state: present

    - name: Create group
      ansible.builtin.user:
        name: "{{ app }}"
        uid: 1111
        password: "{{ password | password_hash('sha512') }}"

    - name: Configure postgres database
      block:
        - name: Create PostgreSQL user
          delegate_to: localhost
          community.postgresql.postgresql_user:
            name: "{{ app }}"
            password: "{{ password }}"
            login_host: db.home
            login_user: cmeadows
            login_password: "{{ password }}"
            db: postgres

        - name: Create PostgreSQL databases
          delegate_to: localhost
          community.postgresql.postgresql_db:
            name: paperless
            state: present
            owner: "{{ app }}"
            encoding: UTF-8
            template: template0
            login_host: db.home
            login_user: cmeadows
            login_password: "{{ password }}"

    - name: Configure paperless
      block:
        - name: Create app folder
          ansible.builtin.file:
            path: /src/{{ app }}
            mode: '0750'
            state: directory

        - name: Create config folder
          ansible.builtin.file:
            path: "/mnt/config/{{ app }}"
            state: directory
            mode: '0750'
            owner: "{{ app }}"
            group: "{{ app }}"

        - name: Copy .env file
          ansible.builtin.copy:
            src: "{{ app }}.env"
            dest: "/src/{{ app }}/.env"

        - name: Copy docker files
          ansible.builtin.template:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
          with_items:
            - src: "{{ app }}_docker-compose.yml.j2"
              dest: "/src/{{ app }}/docker-compose.yml"
            - src: "docker-compose.env.j2"
              dest: "/src/{{ app }}/docker-compose.env"

        - name: Create and start paperless
          community.docker.docker_compose_v2:
            project_src: /src/{{ app }}

- name: Update Caddy
  ansible.builtin.import_playbook: caddy.yml
  vars:
    apps:
      - hostname: "{{ hostvars.vars.host_fqdn }}"
        upstream_host: "{{ hostvars.vars.host_fqdn }}"
        port: 8000