---
- name: Setup Postgres instance
  hosts: postgres
  gather_facts: false
  roles:
    # - update

  tasks:
    - name: Install apt dependencies
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - postgresql
          - python3-pip
          - sudo

    - name: Install pip dependencies
      ansible.builtin.pip:
        name: psycopg2-binary
        extra_args: --break-system-packages
    
    - name: Configure Postgresql
      become: true
      become_user: postgres
      block:
      - name: Set listen_addresses
        community.postgresql.postgresql_set:
          name: listen_addresses
          value: "*"
        notify: Restart postgresql

      - name: Grant access from network
        postgresql_pg_hba:
          dest: /etc/postgresql/15/main/pg_hba.conf
          contype: host
          users: all
          source: 10.0.0.0/24
          databases: all
          method: md5
        notify: Restart postgresql

      - name: Connect to acme database, create django user, and grant access to database and products table
        community.postgresql.postgresql_user:
          name: teahookup
          password: "{{ password }}"
      
      - name: Create a new database with name "teahookup"
        community.postgresql.postgresql_db:
          name: teahookup
          owner: teahookup

  handlers:
    - name: Restart postgresql
      ansible.builtin.service:
        name: postgresql
        state: restarted