---
- name: Add Mountpoint from PVE
  hosts: pve_server
  gather_facts: false
  tasks:
    - name: Stop LXC
      ansible.builtin.command: pct stop {{ lxc_id }}

    - name: Edit config to create /dev/tun
      ansible.builtin.lineinfile:
        path: /etc/pve/lxc/{{ lxc_id }}.conf
        line: "{{ item }}"
      loop:
        - "lxc.cgroup2.devices.allow: c 10:200 rwm"
        - "lxc.mount.entry: /dev/net dev/net none bind,create=dir"

    - name: Start LXC
      ansible.builtin.command: pct start {{ lxc_id }}
