---
- name: Setup Redis instance
  hosts: redis
  roles:
    - update

  tasks:
    - name: Install apt dependencies
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - python3-pip

    - name: Install pip dependencies
      ansible.builtin.pip:
        name: redis
        extra_args: --break-system-packages

    - name: Download Redis GPG key
      ansible.builtin.get_url:
        url: https://packages.redis.io/gpg
        dest: /usr/share/keyrings/redis-archive-keyring.asc
        mode: '0644'

    - name: Add Redis repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.asc] https://packages.redis.io/deb {{ ansible_distribution_release }} main"
        state: present

    - name: Install tools
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400 # One day
        pkg:
          - redis
    
    - name: Ensure Redis is started
      ansible.builtin.service:
        name: redis-server
        state: started
        enabled: true

    - name: Set password for auth
      community.general.redis:
        command: config
        name: requirepass
        value: "{{ password }}"

    - name: Bind redis to {{ ansible_eth0.ipv4.address }}
      ansible.builtin.lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^bind'
        line: bind 127.0.0.1 -::1 10.0.0.206
      notify: Restart Redis

  handlers:
    - name: Restart Redis
      ansible.builtin.service:
        name: redis-server
        state: restarted