---
- name: Preconfigure Jellyfin server
  hosts: video.home
  vars:
    user: jellyfin
    crowdsec_collection: LePresidente/jellyfin
  roles:
    - update
    - dotnet
    - crowdsec

- name: Update LXC .conf
  ansible.builtin.import_playbook: lxc_conf.yml
  vars:
    id: "{{ hostvars.vars.container_id_fact }}"
    lxc_config_block: |
      lxc.cgroup2.devices.allow: a
      lxc.cap.drop:
      lxc.mount.entry: /dev/net dev/net none bind,create=dir
      lxc.mount.entry: /dev/nvidia0 dev/nvidia0 none bind,optional,create=file
      lxc.mount.entry: /dev/nvidiactl dev/nvidiactl none bind,optional,create=file
      lxc.mount.entry: /dev/nvidia-modeset dev/nvidia-modeset none bind,optional,create=file
      lxc.mount.entry: /dev/nvidia-uvm dev/nvidia-uvm none bind,optional,create=file
      lxc.mount.entry: /dev/nvidia-uvm-tools dev/nvidia-uvm-tools none bind,optional,create=file
      dev0: /dev/dri/renderD128,gid=104
      dev1: /dev/dri/renderD129,gid=104
      mp0: /storage/streaming,mp=/mnt/media

- name: Setup Jellyfin server
  hosts: video.home
  vars:
    user: jellyfin
    nvidia_driver: client
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - intel-opencl-icd

    - name: Create {{jellyfin}} group
      ansible.builtin.group:
        name: "{{ user }}"
        gid: 1111
        state: present

    - name: Create {{jellyfin}} user
      ansible.builtin.user:
        name: "{{ user }}"
        uid: 1111
        password: "{{ password | password_hash('sha512') }}"

    - name: Run Nvidia role
      ansible.builtin.include_role:
        name: "{{ item }}"
      with_items:
        - nvidia

    - name: Check if Jellyfin is installed
      ansible.builtin.package_facts:
        manager: apt
      no_log: true

    - name: Install Jellyfin
      when: "'jellyfin' not in ansible_facts.packages"
      block:
        - name: Install software-properties-common
          ansible.builtin.apt:
            pkg:
              - software-properties-common

        # - name: Add Universe repository
        #   apt_repository:
        #     repo: universe
        #     state: present

        - name: Create keyrings directory
          ansible.builtin.file:
            path: /etc/apt/keyrings
            state: directory
            mode: '0755'

        - name: Download and install Jellyfin GPG key
          ansible.builtin.get_url:
            url: https://repo.jellyfin.org/jellyfin_team.gpg.key
            dest: /tmp/jellyfin.gpg.key
          register: gpg_key

        - name: Import GPG key
          shell: cat /tmp/jellyfin.gpg.key | gpg --dearmor -o /etc/apt/keyrings/jellyfin.gpg
          when: gpg_key.changed

        - name: Create Jellyfin repository source
          copy:
            dest: /etc/apt/sources.list.d/jellyfin.sources
            mode: '0644'
            content: |
              Types: deb
              URIs: https://repo.jellyfin.org/{{ ansible_distribution | lower }}
              Suites: {{ ansible_distribution_release }}
              Components: main
              Architectures: {{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}
              Signed-By: /etc/apt/keyrings/jellyfin.gpg

        - name: Update apt cache
          apt:
            update_cache: yes

        - name: Install Jellyfin
          apt:
            pkg: 
            - jellyfin
            state: present

        - name: Ensure Jellyfin service is enabled and started
          systemd:
            name: jellyfin
            state: started
            enabled: yes

        - name: Clean up temporary files
          file:
            path: /tmp/jellyfin.gpg.key
            state: absent

    - name: Add jellyfin user to render group
      ansible.builtin.user:
        name: jellyfin
        groups: render
        append: yes

    # Fileflows
    - name: Create fileflows user
      ansible.builtin.user:
        name: fileflows
        system: true
        create_home: false
        shell: /usr/sbin/nologin

    - name: Check if FileFlows service exists
      ansible.builtin.stat:
        path: /etc/systemd/system/fileflows.service
      register: service_check

    - name: Setup FileFlows
      block:
        - name: Install FileFlows
          when: not service_check.stat.exists
          block:
            - name: Download FileFlows
              ansible.builtin.get_url:
                url: https://fileflows.com/downloads/zip
                dest: /tmp/FileFlows.zip
                mode: '0644'

            - name: Create FileFlows directory
              ansible.builtin.file:
                path: /usr/src/FileFlows
                state: directory
                mode: '0755'
                owner: fileflows
                group: fileflows

            - name: Extract FileFlows
              ansible.builtin.unarchive:
                src: /tmp/FileFlows.zip
                dest: /usr/src/FileFlows
                remote_src: true
                owner: fileflows
                group: fileflows

            - name: Set execute permission on run-server.sh
              ansible.builtin.file:
                path: /usr/src/FileFlows/run-server.sh
                mode: '0755'
                owner: fileflows
                group: fileflows

            - name: Create FileFlows systemd service
              ansible.builtin.copy:
                dest: /etc/systemd/system/fileflows.service
                mode: '0644'
                content: |
                  [Unit]
                  Description=FileFlows

                  [Service]
                  ExecStart=/usr/bin/dotnet /usr/src/FileFlows/Server/FileFlows.Server.dll
                  SyslogIdentifier=FileFlows
                  User=fileflows
                  Restart=always
                  RestartSec=5
                  Environment=DOTNET_ROOT=/usr/lib64/dotnet

                  [Install]
                  WantedBy=multi-user.target

            - name: Start and enable FileFlows service
              ansible.builtin.systemd:
                name: fileflows
                state: started
                enabled: true
                daemon_reload: true

            - name: Clean up zip file
              ansible.builtin.file:
                path: /tmp/FileFlows.zip
                state: absent
