---
- name: Setup VS Code Server
  hosts: vscode-server
  vars:
    user: vscode-server
  roles:
    - update
    - fstab

  tasks:
    - name: Install apt dependencies
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400 # One day
        pkg:
          - python3-pip
          - python3-venv
          - gpg

    - name: Download HashiCorp GPG key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
        mode: '0644'

    - name: Add HashiCorp repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present

    - name: Download Nodesource GPG key
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        dest: /usr/share/keyrings/nodesource.asc
        mode: '0644'

    - name: Add Nodesource repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/nodesource.asc] https://deb.nodesource.com/node_20.x nodistro main"
        state: present

    - name: Download dotnet GPG key
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /usr/share/keyrings/microsoft-prod.asc
        mode: '0644'

    - name: Add dotnet repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64,arm64,armhf signed-by=/usr/share/keyrings/microsoft-prod.asc] https://packages.microsoft.com/debian/12/prod bookworm main"
        state: present

    - name: Install tools
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400 # One day
        pkg:
          - ansible
          - terraform
          - azure-cli
          - nodejs
          - dotnet-sdk-7.0
          - aspnetcore-runtime-7.0

    - name: Copy SSH keys
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ item }}"
        mode: '0400'
      loop:
        - ~/.ssh/pve-server
        - ~/.ssh/pve-server.pub