---
- name: Update and upgrade apt
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400 # One day

- name: Fix ssh slowness # https://gist.github.com/charlyie/76ff7d288165c7d42e5ef7d304245916?permalink_comment_id=4897155#gistcomment-4897155
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-session
    regexp: '^session\s+optional\s+pam_systemd\.so'
    line: '#session optional pam_systemd.so'
    state: present
    backrefs: yes