---
- name: Update and upgrade apt
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400 # One day

- name: Update and upgrade apt
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400 # One day
    pkg:
      - bat
      - curl
      - micro
      - gpg
      - gnupg
      - unzip

- name: Fix ssh slowness # https://gist.github.com/charlyie/76ff7d288165c7d42e5ef7d304245916?permalink_comment_id=4897155#gistcomment-4897155
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-session
    regexp: '^session\s+optional\s+pam_systemd\.so'
    line: '#session optional pam_systemd.so'
    state: present
    backrefs: yes

- name: Add Fish shell repository and key
  block:
    - name: Add Fish repository GPG key
      ansible.builtin.shell: |
        curl -fsSL https://download.opensuse.org/repositories/shells:fish:release:3/Debian_12/Release.key |
        gpg --dearmor > /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg
      args:
        creates: /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg

    - name: Add Fish repository
      ansible.builtin.apt_repository:
        repo: deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_12/ /
        state: present
        filename: shells-fish-release-3

    - name: Install fish
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400 # One day
        pkg:
          - fish

    - name: Set root user shell to fish
      ansible.builtin.user:
        name: root
        shell: /usr/bin/fish

    - name: Set fish as default shell for new users
      ansible.builtin.lineinfile:
        path: /etc/adduser.conf
        regexp: '^DSHELL='
        line: 'DSHELL=/usr/bin/fish'

