---
- name: Initialize empty combined list
  ansible.builtin.set_fact:
    combined_vars: []

- name: Load and combine YAML files
  ansible.builtin.set_fact:
    combined_vars: "{{ combined_vars + [lookup('file', './files/' + item.name + '_docker-compose.yml') | from_yaml] }}"
  loop: "{{ apps }}"

# - name: Use loaded variables
#   ansible.builtin.debug:
#     msg: "Value is {{ combined_vars }}"

- name: Create Caddy configs for services
  ansible.builtin.copy:
    dest: "/usr/local/etc/caddy/caddy.d/{{ item.value.container_name }}.conf"
    mode: '0644'
    content: |
      {{ item.value.container_name }}.home:80 {
          reverse_proxy {{ caddy_dest }}:{{ item.value.ports[0] | regex_replace('^(\d+):.*$', '\1') }}
      }
  loop: "{{ combined_vars | map(attribute='services') | map('dict2items') | flatten }}"
  when: item.value.ports is defined
  notify: Restart caddy
