---
- name: Install dependencies
  ansible.builtin.apt:
    pkg:
      - samba
      - samba-common-bin
      - acl
    cache_valid_time: 86400 # One day

- name: Add users for other services
  ansible.builtin.user:
    name: "{{ item.username }}"
    password: "{{ item.password | password_hash('sha512') }}"
  with_items:
    - "{{ users }}"

- name: Copy smb.conf
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  notify:
    - Restart samba

- name: Create Samba users
  ansible.builtin.shell: >
    set -e -o pipefail
    && (echo '{{ item.password }}'; echo '{{ item.password }}')
    | smbpasswd -s -a {{ item.username }}
  args:
    executable: /bin/bash
  register: samba_create_users
  changed_when: "'Added user' in samba_create_users.stdout"
  with_items:
    - "{{ users }}"
  no_log: true

- name: Set ACL permissions
  ansible.builtin.shell: setfacl -R -m u:{{ item.name }}:rwx {{ item.mount }}
  with_items:
    - "{{ shares }}" # This works instead of {{ users }} because mount names are same as usernames

- name: Copy backup.sh script to the target server
  copy:
    src: backup.sh
    dest: /usr/local/bin/backup.sh
    mode: '0755'  # Make the script executable

- name: Ensure the cron job exists to run backup.sh once a day
  cron:
    name: "Daily Backup"
    job: "/usr/local/bin/backup.sh"
    minute: "0"
    hour: "2"  # This sets the job to run at 2:00 AM every day
    user: root  # Run the cron job as the root user
